
default: &default
  adapter: postgresql
  encoding: unicode



development:
  <<: *default
  database: Bolt_development
  # allow_concurrency: true
  pool: 5


test:
  <<: *default
  database: Bolt_test
  allow_concurrency: true
  pool: 25

production:
  <<: *default
  database: Bolt_production
  username: Bolt
  password: <%= ENV['BOLT_DATABASE_PASSWORD'] %>