
default: &default
  adapter: postgresql
  encoding: unicode



development:
  <<: *default
  database: rivetdev
  allow_concurrency: true
  pool: 25


test:
  <<: *default
  database: rivettest
  allow_concurrency: true
  pool: 25

production:
  <<: *default
  database: rivetproduction
  username: Rivet
  password: <%= ENV['RIVET_DATABASE_PASSWORD'] %>