
default: &default
  adapter: postgresql
  encoding: unicode



development:
  <<: *default
  database: boltdev
  allow_concurrency: true
  pool: 25


test:
  <<: *default
  database: bolttest
  allow_concurrency: true
  pool: 25

production:
  <<: *default
  database: boltproduction
  username: Bolt
  password: <%= ENV['BOLT_DATABASE_PASSWORD'] %>